### ISSUE TITLE
"Unknown app" on Windows 11

### ISSUE THREAD

**Issue by nye-nya** [HenryPDT/mb_MediaControl#2]
On Windows 11, the overlay is shown as "Unknown app":

![U2GU8JuN](https://github.com/user-attachments/assets/aae82bad-9ae6-43c7-9364-87e12fb0bb03)

**Comment by nye-nya** [comment]
more info:
it only happens on the portable version of musicbee, not with the installer version.
it also throws the following error once at musicbee startup

```
10.0.26100.0 - 3.6.9135.37003P - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBeePlugin.Plugin.SetPlayerState()
   at MusicBeePlugin.Plugin.ReceiveNotification(String sourceFileUrl, NotificationType type)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at #=z_MjBSK3opLnAq13HdA==.#=z3UgV4FjL_E5d()
   ```
